[package]
name = "r_unrar"
version = "0.1.0"
authors = ["zacbre <zacbre@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
rand = "0.8.5"
